//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instruction_editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Robot</string>
  <string>Aligner</string>
  <string>Load Port</string>
  <string>OCR</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EquipmentType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EquipmentType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>GET</string>
  <string>SET</string>
  <string>CMD</string>
  <string>FUN</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CommandType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CommandType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Equipment_Type</string>
  <string>Equipment_Supplier</string>
  <string>Command_Type</string>
  <string>Command_ID</string>
  <string>Command_Format</string>
  <string>Command_Name</string>
  <string>Command_Order</string>
  <string>Parameters_Amount</string>
  <string>Parameter_Order</string>
  <string>Parameter_ID</string>
  <string>Parameter_Description</string>
  <string>Data_Value</string>
  <string>Min_Value</string>
  <string>Max_Value</string>
  <string>Default_Value</string>
  <string>Values_length</string>
  <string>Is_Fill</string>
  <string>Action_Function</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Command_Parameter_Columns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Command_Parameter_Columns"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>SANWA</string>\r\n  <string>Kawasaki</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Equipment_Supplier {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Equipment_Supplier"]));
            }
            set {
                this["Equipment_Supplier"] = value;
            }
        }
    }
}
