//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Category_ID</string>
  <string>Category_Description</string>
  <string>Code_Name</string>
  <string>Code_Type</string>
  <string>Code_ID</string>
  <string>Code_Cause</string>
  <string>Code_Cause_English</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Code_Columns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Code_Columns"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>SANWA.Robot,Robot 命令</string>
  <string>KAWASAKI.Robot,Robot 命令</string>
  <string>SANWA.Aligner,Aligner 命令</string>
  <string>KAWASAKI.Aligner,Aligner 命令</string>
  <string>COGNEX.OCR,OCR 命令</string>
  <string>HST.OCR,OCR 命令</string>
  <string>TDK.LoadPort,LoadPort 命令</string>
  <string>00,SANWA Robot Error 機台錯誤訊息</string>
  <string>A0,SANWA Aligner Error 機台錯誤訊息</string>
  <string>11,TDK LoadPort Error 機台錯誤訊息</string>
  <string>System,系統訊息</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Category {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Category"]));
            }
        }
    }
}
